// GENERADO por scripts/generate-academia.js — no editar a mano.
// Espejo slug -> puntos de los catálogos de la academia (validación server-side).
const MODULE_POINTS = {
  'introduccion-al-trading': 10,
  'activos-financieros-basicos': 10,
  'tipos-de-ordenes-mercado': 10,
  'plataformas-configuracion': 10,
  'introduccion-analisis-tecnico': 10,
  'soportes-resistencias-zonas': 10,
  'tendencias-estructura-mercado': 10,
  'velas-japonesas-reversion': 10,
  'patrones-continuacion-cambio': 10,
  'volumen-liquidez': 10,
  'indicadores-tecnicos-esenciales': 15,
  'medias-moviles-cruces': 15,
  'rsi-macd-osciladores': 15,
  'fibonacci-retrocesos-extensiones': 15,
  'gestion-riesgo-posicion': 15,
  'psicologia-control-emocional': 15,
  'plan-trading-profesional': 15,
  'estrategias-scalping': 15,
  'estrategias-day-trading': 15,
  'estrategias-swing-trading': 15,
  'analisis-fundamental-noticias': 20,
  'correlacion-mercados': 20,
  'oferta-demanda-supply-demand': 20,
  'smart-money-concepts': 20,
  'wyckoff-acumulacion-distribucion': 20,
  'liquidez-order-blocks-fvg': 20,
  'backtesting-optimizacion': 20,
  'prop-firms-reglas-fondeo': 20,
  'sistema-trading-rentable': 20,
  'trading-avanzado-automatizacion': 20,
};

const PREMIUM_MODULE_POINTS = {
  'smc-avanzado-liquidez-institucional': 30,
  'order-flow-footprint': 30,
  'volume-market-profile-pro': 30,
  'dom-libro-ordenes': 30,
  'microestructura-instituciones': 30,
  'order-blocks-breakers-avanzado': 30,
  'liquidity-sweeps-manipulacion': 30,
  'backtesting-validacion-estadistica': 30,
  'optimizacion-sistemas-trading': 30,
  'trading-cuantitativo-discrecional': 30,
  'estadistica-probabilidades-trading': 30,
  'gestion-avanzada-drawdown': 30,
  'psicologia-alto-rendimiento': 30,
  'trading-noticias-alto-impacto': 30,
  'intermarket-correlaciones-globales': 30,
  'portafolios-diversificacion-pro': 30,
  'automatizacion-bots-algoritmos': 30,
  'superar-prop-firms-consistente': 30,
  'escalabilidad-capital-cuentas': 30,
  'trading-como-empresa-kpis': 30,
};

module.exports = { MODULE_POINTS, PREMIUM_MODULE_POINTS };
